default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER_NAME") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  host: <%= ENV.fetch("POSTGRES_HOST") %>
  timeout: 5000

development:
  <<: *default
  database: myappdb_development


test:
  <<: *default
  database: myappdb_test

production:
  <<: *default
  database: myappdb_production
